name: Build & Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    permissions:
      contents: write
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        shell: bash
        run: |
          if [ "${{ matrix.os }}" == "macos-latest" ]; then
            npm install
          else
            npm install --no-optional
          fi

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y libdbus-1-dev fakeroot

      - name: Build App
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "${{ matrix.os }}" == "macos-latest" ]; then
            npm run dist:mac
          elif [ "${{ matrix.os }}" == "windows-latest" ]; then
            npm run dist:win
          elif [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            npm run dist:linux
          fi

      - name: Upload Artifacts to Release
        if: success()
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.exe
            dist/*.dmg
            dist/*.AppImage
            dist/*.deb
            dist/*.rpm
            dist/*.snap
            dist/*.zip
            dist/*.tar.gz
            dist/*.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Push to Public Release Repo
        if: success()
        run: |
          git config --global user.name "mrshivamshaw"
          git config --global user.email "shivamshaw9005@gmqail.com"

          git clone https://mrshivamshaw:${{ secrets.GH_TOKEN }}@github.com/mrshivamshaw/electron-app-releases.git release-repo

          mkdir -p release-repo/${{ github.ref_name }}/${{ matrix.os }}
          cp dist/* release-repo/${{ github.ref_name }}/${{ matrix.os }}/

          cd release-repo
          git add .
          git commit -m "Release ${{ github.ref_name }} - ${{ matrix.os }}"
          git push
